<?php
    $title = "Marmitas da Dona Rita";
    $desenvolvedor = "José Roberto dos Santos";

    $tutoriais = array(
        0 => array('id'=>'1', 
            'titulo'=>'Marmita Caseira nº 1',  
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Panqueca e Legumes',
            'imagem'=>'img/foto2.jpg', 
            'title_img'=>'Marmita Caseira nº 1'),
        1 => array('id'=>'2', 
            'titulo'=>'Marmita Caseira nº 2',  
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijoada, Farofa, Bisteca de Porco, Batata Frita e Salada',
            'imagem'=>'img/foto4.jpeg', 
            'title_img'=>'Marmita Caseira nº 2'),
        2 => array('id'=>'3', 
            'titulo'=>'Marmita Caseira nº 3', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Carne de Panela, Macarrão, Legumes e Salada',
            'imagem'=>'img/foto5.jpg', 
            'title_img'=>'Marmita Caseira nº 3'),
        3 => array('id'=>'4', 
            'titulo'=>'Marmita Caseira nº 4', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Bife, Frango e Salada',
            'imagem'=>'img/foto6.jpg', 
            'title_img'=>'Marmita Caseira nº 4'),
        4 => array('id'=>'5', 
            'titulo'=>'Marmita Caseira nº 5', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Picadinho de Carne, Couve e Salada',
            'imagem'=>'img/foto7.jpg', 
            'title_img'=>'Marmita Caseira nº 5'),
        5 => array('id'=>'6', 
            'titulo'=>'Marmita Caseira nº 6', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Picadinho de Carne, Couve e Salada',
            'imagem'=>'img/foto8.jpg', 
            'title_img'=>'Marmita Caseira nº 6'),
        6 => array('id'=>'7', 
            'titulo'=>'Marmita Caseira nº 7', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Picadinho de Carne, Couve e Salada',
            'imagem'=>'img/foto9.png', 
            'title_img'=>'Marmita Caseira nº 7'),
        7 => array('id'=>'8', 
            'titulo'=>'Marmita Caseira nº 8', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Picadinho de Carne, Couve e Salada',
            'imagem'=>'img/foto3.jpg', 
            'title_img'=>'Marmita Caseira nº 8'),
    );